import 'package:flutter/material.dart';
import '../app_widgets.dart';

class SplashScreen extends StatefulWidget{const SplashScreen({super.key});@override State<SplashScreen>createState()=>_S();}
class _S extends State<SplashScreen>{@override void initState(){super.initState();Future.delayed(const Duration(seconds:2),(){if(mounted)Navigator.pushReplacementNamed(context,'/intro');});}@override Widget build(BuildContext c)=>const Scaffold(backgroundColor:bg,body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.arrow_forward_rounded,color:orange,size:80),SizedBox(height:14),Text('Arro Puzzal',style:TextStyle(fontSize:40,fontWeight:FontWeight.bold,color:brown)),Text('Follow the arrows. Clear the path.',style:TextStyle(color:brown))]));}

class IntroScreen extends StatelessWidget{const IntroScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(backgroundColor:bg,body:SafeArea(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.alt_route,color:orange,size:100),const SizedBox(height:20),const Text('Arro Puzzal',style:TextStyle(fontSize:42,fontWeight:FontWeight.bold,color:brown)),const SizedBox(height:12),const Text('Move each arrow in its direction and take it outside the board. Find the right order and clear every arrow.',textAlign:TextAlign.center,style:TextStyle(fontSize:18,color:brown,height:1.5)),const SizedBox(height:35),primary(c,'Start Game',()=>Navigator.pushReplacementNamed(c,'/home'))]))));}

class HomeScreen extends StatelessWidget{const HomeScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(backgroundColor:bg,body:SafeArea(child:Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Spacer(),const Center(child:Text('Arro Puzzal',style:TextStyle(fontSize:42,fontWeight:FontWeight.bold,color:brown))),const SizedBox(height:8),const Center(child:Text('Follow the arrows • Clear the path',style:TextStyle(color:brown))),const SizedBox(height:35),primary(c,'Play',()=>Navigator.pushNamed(c,'/difficulty')),const SizedBox(height:12),Row(children:[softButton('Daily',Icons.today,()=>Navigator.pushNamed(c,'/daily')),softButton('How to Play',Icons.help_outline,()=>Navigator.pushNamed(c,'/how')),softButton('Settings',Icons.settings_outlined,()=>Navigator.pushNamed(c,'/settings'))]),const Spacer(),const Center(child:Text('Daily Streak  🔥  3',style:TextStyle(color:brown,fontWeight:FontWeight.bold))),const SizedBox(height:15)])));}

class DifficultyScreen extends StatelessWidget{const DifficultyScreen({super.key});@override Widget build(BuildContext c)=>AppScaffold(title:'Choose Difficulty',body:ListView(padding:const EdgeInsets.all(22),children:[for(final x in ['Easy','Normal','Hard','Expert'])Card(color:Colors.white,child:ListTile(contentPadding:const EdgeInsets.all(18),title:Text(x,style:const TextStyle(color:brown,fontSize:20,fontWeight:FontWeight.bold)),subtitle:Text(x=='Easy'?'Learn the mechanic':x=='Normal'?'Build your rhythm':x=='Hard'?'Complex paths':'Master the order',style:const TextStyle(color:brown)),trailing:const Icon(Icons.chevron_right,color:brown),onTap:()=>Navigator.pushNamed(c,'/levels'))]));}

class LevelSelectScreen extends StatelessWidget{const LevelSelectScreen({super.key});@override Widget build(BuildContext c)=>AppScaffold(title:'Levels',body:GridView.builder(padding:const EdgeInsets.all(18),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:12,mainAxisSpacing:12),itemCount:30,itemBuilder:(c,i)=>InkWell(onTap:()=>Navigator.pushNamed(c,'/game'),child:Card(color:Colors.white,child:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text('${i+1}',style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold,color:brown)),Text(i<5?'★★★':i<12?'★★☆':'☆',style:const TextStyle(color:orange))])))));}

class ResultScreen extends StatelessWidget{const ResultScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(backgroundColor:bg,body:SafeArea(child:Center(child:Padding(padding:const EdgeInsets.all(26),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Text('Level Complete!',style:TextStyle(fontSize:34,fontWeight:FontWeight.bold,color:brown)),const SizedBox(height:12),const Text('★★★',style:TextStyle(fontSize:42,color:orange)),const SizedBox(height:10),const Text('All arrows escaped the board.',style:TextStyle(color:brown,fontSize:18)),const SizedBox(height:30),primary(c,'Next Level',()=>Navigator.pushReplacementNamed(c,'/game')),const SizedBox(height:12),primary(c,'Level Select',()=>Navigator.pushReplacementNamed(c,'/levels'))]))));}

class SettingsScreen extends StatefulWidget{const SettingsScreen({super.key});@override State<SettingsScreen>createState()=>_Set();}
class _Set extends State<SettingsScreen>{bool sound=true,vibration=true;@override Widget build(BuildContext c)=>AppScaffold(title:'Settings',body:ListView(padding:const EdgeInsets.all(18),children:[SwitchListTile(title:const Text('Sound'),value:sound,onChanged:(v)=>setState(()=>sound=v)),SwitchListTile(title:const Text('Vibration'),value:vibration,onChanged:(v)=>setState(()=>vibration=v)),const ListTile(title:Text('Theme'),subtitle:Text('Warm Light')),const ListTile(title:Text('About'),subtitle:Text('Arro Puzzal • v1.0.0'))]));}}

class DailyScreen extends StatelessWidget{const DailyScreen({super.key});@override Widget build(BuildContext c)=>AppScaffold(title:'Daily Puzzle',body:Padding(padding:const EdgeInsets.all(22),child:Column(children:[const Icon(Icons.local_fire_department,color:orange,size:80),const Text('Daily Streak',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold,color:brown)),const SizedBox(height:10),const Text('Solve today’s special arrow puzzle.',style:TextStyle(color:brown)),const Spacer(),primary(c,'Play Daily Puzzle',()=>Navigator.pushNamed(c,'/game')),const Spacer()]));}

class HowToPlayScreen extends StatelessWidget{const HowToPlayScreen({super.key});@override Widget build(BuildContext c)=>AppScaffold(title:'How to Play',body:ListView(padding:const EdgeInsets.all(22),children:[for(final s in ['1. Tap an arrow.','2. It moves in the direction it points.','3. If another arrow blocks the route, solve/remove that arrow first.','4. Short, medium and long arrows can all appear.','5. Every arrow is guaranteed to have a valid escape path.','6. Clear the last arrow to complete the level.'])Card(color:Colors.white,child:Padding(padding:const EdgeInsets.all(18),child:Text(s,style:const TextStyle(fontSize:17,color:brown,height:1.4))))]));}
